sonar.projectKey=13SOAT-andromeda_video-processor-converter
sonar.organization=13soat-andromeda
sonar.projectName=video-processor-converter
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*_test.go,**/mocks/**,**/cmd/**,**/context/**,**/test/**,**/Dockerfile*

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/adapter/s3/**,**/adapter/sqs/**
